iersion: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 361769582717.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=361769582717.dkr.ecr.ap-south-1.amazonaws.com/eks-nodejs-repo
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      - echo Building Docker image...
      - docker build -t eks-nodejs-repo .
      - docker tag eks-nodejs-repo:latest $REPOSITORY_URI:$IMAGE_TAG
      - docker tag eks-nodejs-repo:latest $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - echo Writing imagedefinitions.json...
      - printf '[{"name":"nodejs-app","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - deploy/deployment.yaml
    - deploy/service.yaml
