apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-container
          image: 361769582717.dkr.ecr.ap-south-1.amazonaws.com/eks-nodejs-repo:latest  # Replace during pipeline or manually
          ports:
            - containerPort: 443
